Smartling/wordpress-localization-plugin

tests/IntegrationTests/tests/TaxonomyTest.php

@paveldhq ~~please note that first test `testSubmitPostWithCategoryWhichHasParentCategory` doesn't work because of unknown reasons (submission's `last_error` column contains value `locale is required`). **But** second test (where cloned submission is being tested) works fine. Moreover when you try to do all the steps from the first test manually then it works as well (I can see 3 submissions in the database).~~

Added test: submit post with category which has parent

---

smartling-connector.php

To avoid throwing PHP notices when other plugins or config already define `SCRIPT_DEBUG`, its definition should be tested before calling `define()`.
I disagree with hardcoding this to true if it's not already explicitly defined on live sites as well - is there a good reason to force worse performance on users?

fix: remove SCRIPT_DEBUG

---

js/smartling-connector-admin.js
readme.txt
smartling-connector.php

The issue is not in WP `wp_send_json` function, it works fine. the issue is that we switched from manual response sending to `wp_send_json` this one which sets `Content-type: application/json` header and `jquery.post` method is smart enough to parse the response for you. So, the issue that we tried to parse already parsed string (js object).
We have a commit `removed JSON.parse() calls because of using wp_send_json() on backend` which removes all such `JSON.parse` line but one line wasn't removed.
Also, @dimitrystd, it's strange that at wp site our plugin has `1.11.1` version (https://wordpress.org/plugins/smartling-connector/) but in repo we have only `1.11.0` tag. Is something messed up with releases?

Missing change since "removed JSON.parse() calls because of using wp_send_json() on backend" (eb683411cb9520b6f16c13a6ebc32ace643f6817) commit

---

composer.json
inc/Smartling/WP/View/ContentEditJob.php
readme.txt
smartling-connector.php

I've used to know that dashes in slugs should not be used, but can't find a good source (https://docs.pluginize.com/article/135-dashes-in-post-type-taxonomy-slugs-for-url-seo)

allow dashes in post type slug for bulk submit (WP-529)

---

inc/Smartling/Services/ContentRelationsDiscoveryService.php
readme.txt
tests/IntegrationTests/tests/NewCategoryIsAttachedToPostOnDownloadTest.php
tests/IntegrationTests/tests/TaxonomyTest.php

Previously, blocks got duplicated if multiple were used on same page. By adding the block index, we're able to process all blocks.

Ingest all blocks

---

inc/Smartling/WP/Controller/TaxonomyLinksController.php

Page not intended for use on network admin, requires specific source blog

Don't show taxonomy links menu on network admin

---

inc/Smartling/Base/SmartlingCoreUploadTrait.php
inc/Smartling/Bootstrap.php
inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php
readme.txt

This also seems to resolve non-translated menu items not being visible after translation due to broken metadata

fix relations after menu translation (WP-589)

---

composer.lock
inc/Smartling/Base/ExportedAPI.php
inc/Smartling/Base/SmartlingCore.php
inc/Smartling/Base/SmartlingCoreUploadTrait.php
inc/Smartling/Jobs/UploadJob.php
inc/Smartling/Submissions/SubmissionManager.php
readme.txt
smartling-connector.php
tests/Smartling/Submissions/SubmissionManagerTest.php

When cloning submissions, they previously applied XML immediatelyat upload job run. This could cause issues when a posts relation was not yet processed, resulting in copying the relation ids instead of altering them as needed. After this PR, every cloned submission first creates target content, then XML is applied with all existing relations having proper target ids.

change cloning workflow (WP-647)

---

inc/Smartling/Base/SmartlingCoreUploadTrait.php
inc/Smartling/Helpers/GutenbergBlockHelper.php
inc/Smartling/Helpers/Serializers/SerializerJsonWithFallback.php
inc/Smartling/Helpers/XmlHelper.php
inc/config/serializer.yml
inc/config/services.yml
tests/Smartling/Base/SmartlingCoreTest.php
tests/Smartling/Base/SmartlingCoreUploadTraitTest.php
tests/Smartling/Helpers/GutenbergBlockHelperTest.php

Switching to json serializer immediately would break existing translation jobs. For now, we need to add a fallback unserialization procedure for these.

add json serializer with fallback (WP-663)

---

composer.json
composer.lock
inc/Smartling/Jobs/UploadJob.php
inc/Smartling/Submissions/SubmissionManager.php
readme.txt
smartling-connector.php
tests/IntegrationTests/SmartlingUnitTestCaseAbstract.php
tests/IntegrationTests/tests/CloneTest.php
tests/IntegrationTests/tests/GutenbergBlocksTest.php

What previously happened was an attachment being created two times: first because it was detected by related media processor, second because it was queued for cloning. Now we get submissions for cloning not in bulk, but one by one, thus on second run we already know it was cloned to the target blog

fix media library items duplication when cloning (WP-675)

---

composer.json
composer.lock
inc/Smartling/Base/SmartlingCoreUploadTrait.php
inc/Smartling/Jobs/LastModifiedCheckJob.php
inc/Smartling/Submissions/SubmissionManager.php
readme.txt
smartling-connector.php
tests/Jobs/LastModifiedCheckJobTest.php
tests/Smartling/Submissions/SubmissionManagerTest.php

Cloned submissions were attempting to do a status check. No file is present, and this error is considered unrecoverable, failing the submission.

Exclude cloned submissions from status checks (WP-684)

---

composer.json
composer.lock
inc/Smartling/DbAl/WordpressContentEntities/EntityAbstract.php
inc/Smartling/DbAl/WordpressContentEntities/PostEntityStd.php
inc/Smartling/DbAl/WordpressContentEntities/TaxonomyEntityStd.php
inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php
inc/Smartling/Extensions/AcfOptionPages/AcfOptionEntity.php
inc/Smartling/Helpers/WordpressFunctionProxyHelper.php
readme.txt
smartling-connector.php
tests/Smartling/DbAl/WordpressContentEntities/TaxonomyEntityStdTest.php

The issue is that WordPress returns an array of values for get_term_meta, and we need to normalize this array just as is done for posts

add meta values normalization for taxonomies (WP-704)

---

Buildplan/Dockerfile-Jenkins
Buildplan/releaseVersionCheck.sh
Jenkinsfile

It is possible to release a non-stable version, and the process of reverting such a release is non-trivial. I remember the idea of releasing by GH tag, but it needs more effort, and would be prone to the same mistake too

add release version check (WP-712)

---

composer.json
inc/Smartling/ContentTypes/ExternalContentManager.php
inc/Smartling/Services/ContentRelationsDiscoveryService.php
readme.txt
smartling-connector.php
tests/Smartling/ContentTypes/ExternalContentManagerTest.php

Visibility PR, I mistakengly thought Exception is a subset of Error, so any exceptions inside external content handlers could break the translation flow.

fix ExternalContentManager error handling (WP-746)

---

composer.json
composer.lock
inc/Smartling/ContentTypes/ExternalContentElementor.php
inc/Smartling/DbAl/WordpressContentEntities/EntityAbstract.php
inc/Smartling/DbAl/WordpressContentEntities/PostEntityStd.php
inc/Smartling/DbAl/WordpressContentEntities/TaxonomyEntityStd.php
inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php
inc/Smartling/Extensions/AcfOptionPages/AcfOptionEntity.php
readme.txt
smartling-connector.php
tests/Smartling/ContentTypes/ExternalContentElementorTest.php

Previously, a fix was applied to lessen the amount of escaping-related issues while saving post_content field. It worked, and now it appears we need to rollout the same for meta fields and other relevant post fields

fix metadata escaping (WP-747)

---

inc/Smartling/Helpers/GutenbergBlockHelper.php
inc/Smartling/Helpers/MetaFieldProcessor/CloneValueFieldProcessor.php

I've examined previous logs, notices regarding cdata sections were present for quite a long time, as well as cloning failure messages. Cdata sections are actually processed along with content chunks. Failures to clone arise due to MetaFieldProcessor trying to process fields from Gutenberg blocks as metadata, but I can't imagine a proper fix for this condition right now

demote logging (WP-767)

---

inc/Smartling/Jobs/UploadJob.php
inc/Smartling/Submissions/SubmissionManager.php
readme.txt
tests/Jobs/UploadJobTest.php
tests/Smartling/Submissions/SubmissionManagerTest.php

There is logging in JobAbstract, but it would help to fail submissions, so the user wouldn't need to purge the queue manually. Also, a failure reason would persist in submission.

add exception handling in UploadJob (WP-776)

---

inc/Smartling/Services/ContentRelationsDiscoveryService.php
tests/Services/ContentRelationDiscoveryServiceTest.php

there was no usage of field names, yet they were messing with the later discovered ids of post-based content

refactor ContentRelationDiscoveryService (WP-786)

---

composer.json
inc/Smartling/ContentTypes/ExternalContentElementor.php
readme.txt
smartling-connector.php

It looks like they've set the plugin to auto-update and ignored the error message, not sure what can be done to improve awareness.
The error message is displayed on every admin page:
and when updating manually, there is also

bump Elementor support version (WP-789)

---

composer.json
inc/Smartling/WP/Controller/TranslationLockController.php
readme.txt
smartling-connector.php
tests/Smartling/WP/Table/SubmissionTableWidgetTest.php

A missing content type check when working with locking UI could result in locking an unintended submission

fix submissions locking (WP-791)

---

inc/Smartling/WP/View/ContentEditJob.php
inc/Smartling/WP/View/taxonomy-based-content-type.php

from some point, WordPress changed form width for taxonomy pages to equal 800px, this is less than was expected, and caused weird display on these pages

change taxonomy pages widget styles (WP-797)

---

inc/Smartling/ContentTypes/ContentTypePluggableInterface.php
inc/Smartling/ContentTypes/ExternalContentAbstract.php
inc/Smartling/ContentTypes/ExternalContentAioseo.php
inc/Smartling/ContentTypes/ExternalContentBeaverBuilder.php
inc/Smartling/ContentTypes/ExternalContentElementor.php
inc/Smartling/ContentTypes/ExternalContentGravityForms.php
inc/Smartling/ContentTypes/ExternalContentManager.php
tests/Smartling/ContentTypes/ExternalContentBeaverBuilderTest.php
tests/Smartling/ContentTypes/ExternalContentElementorTest.php
tests/Smartling/ContentTypes/ExternalContentManagerTest.php

Root cause of issue was unsupported plugin version. Research took some time because I tried reproducing the issue. To avoid this in the future, I propose to remove content that is obviously unsuitable for translation in cases we detect an unsupported version of a plugin

remove fields on unsupported plugin version (WP-814)

---

inc/Smartling/Services/BlogRemovalHandler.php
inc/Smartling/Settings/ConfigurationProfileEntity.php
inc/Smartling/Settings/SettingsManager.php
inc/config/register-on-startup.yml
inc/config/services.yml

The cause of increased warnings count is not a loop. On bootstrap, the plugin tries to get a profile list, for which it generates labels based on blog settings. If a blog does not exist, a warning is generated.

add profile changes on blog removal, clean up profiles on bootstrap (WP-816)

---

inc/Smartling/Helpers/PlaceholderHelper.php
inc/Smartling/Helpers/ShortcodeHelper.php
inc/config/services.yml
tests/MetadataSerializerTest.php
tests/Smartling/Helpers/PlaceholderHelperTest.php
tests/Smartling/Helpers/ShortcodeHelperTest.php

The connector uses the shortcodes that are registered in WP or added in fine-tuning section. It appears the fine-tuning was not set up, as when testing locally with the proper setup, no `#sl-start#` or `#sl-end#` tags appear. Without setting up the fine-tuning, the result is as experienced by the reporter. I'll update the documentation accordingly, but this PR could also help to resolve the issue. The plugin only wraps registered shortcodes in said tags, and the potential for false-positives is quite low, I believe.
I could think of no other way to determine shortcodes presence, as a string that looks like a WP shortcode `[text]` might as well be plain text that is meant for translation.

use Smartling placeholders for shortcode detection (WP-879)

---

composer.json
inc/Smartling/Services/ContentRelationsDiscoveryService.php
readme.txt
smartling-connector.php
tests/Services/ContentRelationDiscoveryServiceTest.php

`array_unique()`, when removing an element that is not the last from an array turns a list (json encoded as `['a', 'b']`) into a map (json encoded as `{"0":"a","2":"b"}`)

fix batch creation error (WP-907)

---

composer.json
inc/Smartling/Services/ContentRelationsDiscoveryService.php
readme.txt
smartling-connector.php
tests/Services/ContentRelationsDiscoveryServiceTest.php

There is in fact an improvement that comes out of the issue described, two other issues are config and/or other plugins related

add support for ACF `relation` field groups (WP-911)

---

composer.json
inc/Smartling/Bootstrap.php
readme.txt
smartling-connector.php

Log introduced temporarily, and is no longer needed

remove log (WP-914)

---

composer.json
inc/Smartling/Bootstrap.php
inc/Smartling/DbAl/WordpressContentEntities/PostEntityStd.php
inc/Smartling/Services/GlobalSettingsManager.php
inc/Smartling/WP/View/ConfigurationProfiles.php
js/configuration-profile-form.js
readme.txt
smartling-connector.php
tests/Mocks/WordpressFunctionsMockHelper.php

Escaping and slashing in the connector is fine.
The issue seems to be similar to an unsolved post from a long ago (https://support.advancedcustomfields.com/forums/topic/backslashes-being-added-to-page-post-content/)
This option might not solve the issue, but we'll have more info for the next iteration.

add option to skip ACF filter removal (WP-913)

---

composer.json
inc/Smartling/ContentTypes/Elementor/DocumentsManagerWrapper.php
inc/Smartling/ContentTypes/ExternalContentElementor.php
readme.txt
smartling-connector.php

The issue occurred in the following sequence of events:
1. our plugin saves the post content
2. Elementor hook processes content, looks at metadata (there is none), caches the template type internally as the first available type (loop-item)
3. our plugin saves metadata
4. if Elementor elements are present in template, our plugin calls Elementor after save hook, but the template type there is read from cache instead of metadata and persists
Refactored Elementor elements present check and added a wrapper to clear Elementor Documents_Manager internal cache

clear Elementor built-in documents cache after saving meta (WP-938)
