Smartling/wordpress-localization-plugin

inc/Smartling/Helpers/ShortcodeHelper.php, tests/DetectChangesTest.php, tests/Smartling/Helpers/ShortcodeHelperTest.php, tests/Traits/DbAlMock.php
Careful read of CDATA section of XML
=> Wp 434: Reimplement how we read CDATA section

composer.json, inc/Smartling/ApiWrapper.php, inc/Smartling/Base/SmartlingCoreUploadTrait.php, inc/Smartling/DITrait.php, inc/Smartling/DebugTrait.php, inc/Smartling/Helpers/TranslationHelper.php, inc/Smartling/Settings/ConfigurationProfileEntity.php, inc/Smartling/Submissions/SubmissionManager.php, inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php, inc/Smartling/WP/Controller/TaxonomyWidgetController.php, inc/Smartling/WP/Table/BulkSubmitTableWidget.php, inc/config/services.yml, tests/Smartling/Base/SmartlingCoreTest.php, tests/Traits/SettingsManagerMock.php, tests/Traits/SubmissionManagerMock.php
- added logging with traces when faced submissions without batchUid on upload
- added more strict logic to handle such issue on submission creation
- added logic that tries to get batchUid if needed.
=> [WP-448] Improve batchUid handling on upload

inc/Smartling/Helpers/SubmissionCleanupHelper.php
`\ArgumentCountError` on multiple taxonomy remove
=> remove handler deregister-register magic which causes

inc/Smartling/Helpers/ShortcodeHelper.php
due to update in `wp-include/shortcodes.php:140` `function has_shortcode()` added additional check that now requires rewrite of original registered shortcodes to run.
=> WP-485 Virtual shortcode support broken.

inc/Smartling/Jobs/DownloadTranslationJob.php, inc/Smartling/Jobs/JobAbstract.php, inc/Smartling/Jobs/LastModifiedCheckJob.php, inc/Smartling/Jobs/UploadJob.php
- upload
- check status
- download
=> Automated cron log flag renewal for

composer.json, inc/Smartling/Base/SmartlingCore.php, inc/Smartling/Bootstrap.php, inc/Smartling/Helpers/SiteHelper.php, inc/Smartling/Services/ContentRelationsDiscoveryService.php, readme.txt, smartling-connector.php
fix time submitted display on translation progress page
fix ACF integration
=> release v1.12.4

composer.json, inc/Smartling/Base/SmartlingCoreUploadTrait.php, inc/Smartling/Bootstrap.php, inc/Smartling/Exception/SmartlingManualRelationsHandlingSubmissionCreationForbiddenException.php, inc/Smartling/Helpers/AbsoluteLinkedAttachmentCoreHelper.php, inc/Smartling/Helpers/GutenbergBlockHelper.php, inc/Smartling/Helpers/TranslationHelper.php, inc/Smartling/Services/GlobalSettingsManager.php, inc/Smartling/Settings/ConfigurationProfileEntity.php, inc/Smartling/WP/View/ConfigurationProfiles.php, inc/Smartling/WP/View/ContentEditJob.php, inc/Smartling/WP/WPAbstract.php, js/configuration-profile-form.js, js/smartling-connector-admin.js, readme.txt, smartling-connector.php, tests/Smartling/Helpers/GutenbergBlockHelperTest.php
All changes from previous pull requests to release 1.13.2
=> Release 1.13.2

.phpstorm.meta.php, inc/Smartling/DbAl/WordpressContentEntities/EntityAbstract.php, inc/Smartling/DbAl/WordpressContentEntities/PostEntityStd.php, inc/Smartling/DbAl/WordpressContentEntities/TaxonomyEntityStd.php, inc/Smartling/DbAl/WordpressContentEntities/WidgetEntity.php, inc/Smartling/Extensions/AcfOptionPages/AcfOptionEntity.php, inc/Smartling/Helpers/ContentHelper.php, inc/Smartling/Helpers/WidgetHelper.php, inc/config/services.yml, readme.txt, tests/Services/ContentRelationDiscoveryServiceTest.php, tests/Smartling/DbAl/WordpressContentEntities/EntityAbstractTest.php, tests/Smartling/Extensions/Acf/AcfTypeDetectorTest.php
remove seemingly useless clone function in EntityAbstract
remove ContentHelper WordpressFunctionProxyHelper dependency
=> remove EntityAbstract->__clone(), set 1.15.1 stable, fix TaxonomyEntityStd->setMetaTag()

composer.json, composer.lock, inc/Smartling/Services/ContentRelationsDiscoveryService.php, inc/Smartling/Settings/ConfigurationProfileEntity.php, inc/Smartling/Settings/Locale.php, readme.txt, smartling-connector.php
bugfix release, PR for visibility
=> fix new profile creation

inc/Smartling/Submissions/SubmissionManager.php, tests/Services/ContentRelationDiscoveryServiceTest.php
visibility PR, empty job name was actually being stored, causing no display in row
=> fix for WP-605

build/assets/js/smartling-lock-id.js, build/assets/js/smartling-locked.js, composer.json, composer.lock, inc/Smartling/Bootstrap.php, inc/Smartling/Helpers/EntityHelper.php, inc/Smartling/Services/GlobalSettingsManager.php, inc/Smartling/WP/Controller/BulkSubmitController.php, inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php, inc/Smartling/WP/Table/BulkSubmitTableWidget.php, inc/Smartling/WP/View/ConfigurationProfiles.php, js/configuration-profile-form.js, js/smartling-connector-admin.js, readme.txt, smartling-connector.php, tests/Smartling/WP/Table/BulkSubmitTableWidgetTest.php
includes changes from #298 and #299
=> release 2.4.9

composer.json, composer.lock, inc/Smartling/Helpers/CustomMenuContentTypeHelper.php, inc/Smartling/Services/ContentRelationsDiscoveryService.php, inc/Smartling/WP/View/ContentEditJob.php, inc/config/services.yml, readme.txt, smartling-connector.php, tests/Services/ContentRelationDiscoveryServiceTest.php
includes changes from #317 and #315
=> visibility PR for release 2.6.0

inc/Smartling/Helpers/ContentSerializationHelper.php, inc/config/services.yml, readme.txt, smartling-connector.php, tests/Mocks/WordpressFunctionsMockHelper.php
Includes minor refactoring and cleanup
=> release 2.9.0

composer.lock, inc/Smartling/Services/ContentRelationsHandler.php, readme.txt, smartling-connector.php, tests/Services/ContentRelationsHandlerTest.php
visibility PR, issue discovered while manually testing 2.11.2 after its release
=> fix sending if no related content present (WP-685)

composer.json, composer.lock, inc/Smartling/ContentTypes/AutoDiscover/PostTypes.php, inc/Smartling/Helpers/ArrayHelper.php, inc/Smartling/Models/CloneRequest.php, inc/Smartling/Models/JobInformation.php, inc/Smartling/Models/TranslationRequest.php, inc/Smartling/Services/ContentRelationsDiscoveryService.php, inc/Smartling/Services/ContentRelationsHandler.php, inc/Smartling/WP/View/ContentEditJob.php, readme.txt, smartling-connector.php, tests/Models/CloneRequestTest.php, tests/Models/TranslationRequestTest.php, tests/Services/ContentRelationDiscoveryServiceTest.php, tests/Services/ContentRelationsHandlerTest.php
I've previously introduced a regression in handling, while fixing 2 levels deep cloning issues. Fixed, tests added
=> fix translation request handling (WP-609)

composer.json, readme.txt, smartling-connector.php
=> release 2.12.5

inc/Smartling/Services/ContentRelationsDiscoveryService.php, inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php, inc/Smartling/WP/Table/SubmissionTableWidget.php, tests/Services/ContentRelationDiscoveryServiceTest.php
An exception in api caused uploads to fail, this should not happen
=> catch Api error on audit log creation (WP-714)

composer.json, inc/Smartling/Base/SmartlingCore.php, inc/Smartling/Base/SmartlingCoreTrait.php, inc/Smartling/Base/SmartlingCoreUploadTrait.php, inc/Smartling/ContentTypes/ContentTypePluggableInterface.php, inc/Smartling/ContentTypes/ExternalContentAioseo.php, inc/Smartling/ContentTypes/ExternalContentManager.php, inc/Smartling/DbAl/DB.php, inc/Smartling/DbAl/SmartlingToCMSDatabaseAccessWrapperInterface.php, inc/Smartling/Helpers/FieldsFilterHelper.php, inc/Smartling/Helpers/PluginHelper.php, inc/Smartling/Services/ContentRelationsDiscoveryService.php, inc/Smartling/Submissions/SubmissionEntity.php, inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php, inc/Smartling/WP/Table/SubmissionTableWidget.php, inc/config/services.yml, readme.txt, smartling-connector.php, tests/Services/ContentRelationDiscoveryServiceTest.php, tests/Smartling/Base/SmartlingCoreTest.php, tests/Smartling/Base/SmartlingCoreUploadTraitTest.php, tests/Smartling/ContentTypes/ExternalContentAioseoTest.php, tests/Smartling/Helpers/PluginHelperTest.php
Includes changes from #383, #384 and #385
=> visibility PR for release 2.13.0

composer.json, inc/Smartling/Services/BaseAjaxServiceAbstract.php, inc/Smartling/Services/ContentRelationsDiscoveryService.php, inc/Smartling/Services/ContentRelationsHandler.php, inc/Smartling/Submissions/SubmissionFactory.php, inc/Smartling/WP/View/BulkSubmit.php, inc/Smartling/WP/View/ConfigurationProfileForm.php, inc/Smartling/WP/View/ContentEditJob.php, inc/Smartling/WP/View/post-based-content-type.php, inc/Smartling/WP/View/taxonomy-based-content-type.php, inc/Smartling/WP/WPAbstract.php, inc/config/services.yml, js/smartling-connector-admin.js, readme.txt, smartling-connector.php, tests/Services/ContentRelationDiscoveryServiceTest.php
includes changes from #387, #388 and #389
=> visibility PR for release 2.13.1

composer.json, inc/Smartling/Base/ExportedAPI.php, inc/Smartling/Base/SmartlingCoreUploadTrait.php, inc/Smartling/Bootstrap.php, inc/Smartling/Helpers/PostContentHelper.php, inc/Smartling/Models/NotificationParameters.php, inc/Smartling/WP/Controller/LiveNotificationController.php, readme.txt, smartling-connector.php, tests/Services/ContentRelationDiscoveryServiceTest.php, tests/Smartling/Helpers/PostContentHelperTest.php, tests/Smartling/Helpers/Resources/WP733_expected.html, tests/Smartling/Helpers/Resources/WP733_original.html, tests/Smartling/Helpers/Resources/WP733_original_blocks.json, tests/Smartling/Helpers/Resources/WP733_translated.html, tests/Smartling/Helpers/Resources/WP733_translated_blocks.json
Includes changes from #395 and #396
=> Visibility PR for release 2.13.4

inc/Smartling/Helpers/StringHelper.php
metadata might be null, causing critical errors
=> allow null values for StringHelper string shrink functions (WP-754)

composer.json, inc/Smartling/DbAl/WordpressContentEntities/EntityAbstract.php, inc/Smartling/Helpers/QueryBuilder/QueryBuilder.php, inc/Smartling/Helpers/ShortcodeHelper.php, inc/Smartling/Helpers/SubstringProcessorHelperAbstract.php, inc/Smartling/Services/ContentRelationsDiscoveryService.php, inc/Smartling/Submissions/SubmissionEntity.php, inc/Smartling/Tuner/CustomizationManagerAbstract.php, inc/Smartling/Tuner/ManagerInterface.php, inc/Smartling/Tuner/MediaAttachmentRulesManager.php, readme.txt, smartling-connector.php, tests/Smartling/Base/SmartlingCoreTest.php, tests/Smartling/ContentTypes/ExternalContentManagerTest.php, tests/Smartling/Helpers/PluginHelperTest.php
Visibility PR, includes changes from #424 and partial changes from #423
=> Wp 765 debug and php 8

composer.json, inc/Smartling/ContentTypes/ExternalContentElementor.php, readme.txt, smartling-connector.php
=> bump versions (WP-773)

.phpstorm.meta.php, inc/Smartling/DbAl/WordpressContentEntities/EntityAbstract.php
The error is related to being unable to get a post, this should not happen as we have the id, and it's definitely present in the source blog. It's possible they switch to another blog.
=> add debug (WP-772)

tests/IntegrationTests/tests/PlaceholdersTest.php
We need to document the usage, but for now, everything seems to work, I'll just add a test to prevent any regression
=> add test (WP-779)

inc/Smartling/Extensions/Acf/AcfDynamicSupport.php
These fields are from ACF, so no action for now
=> log error (WP-801)

composer.json, inc/Smartling/Helpers/ContentHelper.php, inc/Smartling/Helpers/RuntimeCacheHelper.php, inc/Smartling/Services/ContentRelationsDiscoveryService.php, readme.txt, smartling-connector.php, tests/Smartling/Helpers/ContentHelperTest.php
=> fix related submissions file names (WP-806)

composer.json, inc/Smartling/Base/SmartlingCoreUploadTrait.php, inc/Smartling/ContentTypes/ExternalContentBeaverBuilder.php, readme.txt, smartling-connector.php
use snapshot of original strings instead of relying on current strings from source blog
=> rework beaver builder original strings (WP-744)

inc/Smartling/Base/SmartlingCore.php, inc/Smartling/Base/SmartlingCoreUploadTrait.php, inc/Smartling/ContentTypes/ContentTypeManager.php, inc/Smartling/ContentTypes/ContentTypeNavigationMenu.php, inc/Smartling/ContentTypes/CustomPostType.php, inc/Smartling/ContentTypes/CustomTaxonomyType.php, inc/Smartling/ContentTypes/CustomTypeTrait.php, inc/Smartling/Helpers/WordpressFunctionProxyHelper.php, tests/IntegrationTests/tests/RelationsTest.php
only search for already translated items on translation download
=> rework related taxonomy content processing (WP-811)

composer.json, inc/Smartling/Base/SmartlingCoreUploadTrait.php, inc/Smartling/Submissions/SubmissionEntity.php, readme.txt, smartling-connector.php
this currently does not happen when uploading files to a single locale
=> remove batch uid when changing submission status to In Progress (WP-807)

js/smartling-connector-gutenberg-lock-attributes.js
this should satisfy both cases when attributes should be added immediately and after DOM load
=> use interval to add lock attributes (WP-808)

inc/Smartling/Base/SmartlingLogHandler.php, inc/Smartling/DITrait.php, inc/config/logger.yml
Resulting log lines start with [2023-08-11 09:49:25.641179]
=> add microseconds to log output (WP-822)

composer.json, inc/Smartling/ContentTypes/ExternalContentElementor.php, readme.txt, smartling-connector.php
I've downloaded 3.15 and tested the new accordion widget, it works
=> Mark Elementor 3.15 supported (WP-824)

composer.json, inc/Smartling/Base/ExportedAPI.php, inc/Smartling/WP/Table/BulkSubmitTableWidget.php, inc/Smartling/WP/View/BulkSubmit.php, readme.txt, smartling-connector.php
WordPress doesn't allow to get posts order by status
=> add bulk submit screen filter api, remove broken status filtering (WP-831)

composer.json, inc/Smartling/DITrait.php, inc/Smartling/Helpers/ContentHelper.php, inc/Smartling/Helpers/PluginInfo.php, inc/Smartling/Services/ContentRelationsDiscoveryService.php, inc/Smartling/Submissions/SubmissionEntity.php, inc/Smartling/Submissions/SubmissionManager.php, inc/Smartling/WP/Controller/ConfigurationProfilesController.php, inc/Smartling/WP/Table/QueueManagerTableWidget.php, inc/Smartling/WP/Table/SubmissionTableWidget.php, inc/config/logger.yml, inc/config/plugin-info.yml, inc/config/services.yml, readme.txt, smartling-connector.php, tests/Services/ContentRelationDiscoveryServiceTest.php, tests/Smartling/Extensions/Acf/AcfTypeDetectorTest.php, tests/Smartling/Helpers/ContentHelperTest.php
Should help if upload queue gets purged
=> add upload queue purge confirmation, add translation progress upload action (WP-839)

composer.json, inc/Smartling/Helpers/GutenbergBlockHelper.php, inc/Smartling/Helpers/PostContentHelper.php, readme.txt, smartling-connector.php, tests/IntegrationTests/tests/LockGutenbergBlockTest.php
Adding a nested Gutenberg block and locking it caused the connector to throw a fatal error while trying to download the content
=> add check source block exists (WP-852) 

composer.json, inc/Smartling/Base/ExportedAPI.php, inc/Smartling/ContentTypes/ExternalContentElementor.php, inc/Smartling/DbAl/DB.php, inc/Smartling/DbAl/SmartlingToCMSDatabaseAccessWrapperInterface.php, inc/Smartling/Exception/SmartlingImpersonationFailedException.php, inc/Smartling/Helpers/ContentHelper.php, inc/Smartling/Helpers/UserHelper.php, inc/Smartling/Helpers/WordpressFunctionProxyHelper.php, inc/config/services.yml, readme.txt, smartling-connector.php, tests/Smartling/ContentTypes/ExternalContentElementorTest.php
The issue was with Elementor checking the permissions, and cron user has no permissions
=> add impersonation (WP-865)

composer.json, inc/Smartling/ContentTypes/ContentTypePluggableInterface.php, inc/Smartling/ContentTypes/ExternalContentAbstract.php, inc/Smartling/ContentTypes/ExternalContentAioseo.php, inc/Smartling/ContentTypes/ExternalContentBeaverBuilder.php, inc/Smartling/ContentTypes/ExternalContentElementor.php, inc/Smartling/ContentTypes/ExternalContentGravityForms.php, inc/Smartling/ContentTypes/ExternalContentManager.php, inc/Smartling/Extensions/Pluggable.php, inc/Smartling/Extensions/PluggableAbstract.php, inc/Smartling/Extensions/Redirection.php, inc/Smartling/Extensions/StringHandler.php, inc/Smartling/Helpers/LinkProcessor.php, inc/Smartling/Helpers/WordpressFunctionProxyHelper.php, inc/Smartling/Helpers/WordpressLinkHelper.php, inc/Smartling/Jobs/JobAbstract.php, inc/Smartling/Services/HandlerManager.php, inc/Smartling/WP/Controller/ConfigurationProfilesController.php, inc/Smartling/WP/Table/BulkSubmitTableWidget.php, inc/Smartling/WP/Table/SubmissionTableWidget.php, inc/config/services.yml, readme.txt, smartling-connector.php, tests/IntegrationTests/tests/ElementorTest.php, tests/Smartling/ContentTypes/ExternalContentBeaverBuilderTest.php, tests/Smartling/ContentTypes/ExternalContentElementorTest.php, tests/Smartling/ContentTypes/ExternalContentManagerTest.php, tests/Smartling/Helpers/LinkProcessorTest.php, tests/Smartling/WP/Table/BulkSubmitTableWidgetTest.php, tests/Smartling/WP/Table/SubmissionTableWidgetTest.php
=> add support for redirection plugin (WP-869)

inc/Smartling/Base/SmartlingCoreTrait.php, inc/Smartling/Helpers/ContentSerializationHelper.php, inc/Smartling/Helpers/FieldsFilterHelper.php, inc/Smartling/Helpers/GutenbergBlockHelper.php, inc/Smartling/Helpers/SubstringProcessorHelperAbstract.php, inc/Smartling/Helpers/XmlHelper.php, inc/config/services.yml, tests/MetadataSerializerTest.php, tests/Services/ContentRelationDiscoveryServiceTest.php, tests/Smartling/Base/SmartlingCoreTest.php, tests/Smartling/Base/SmartlingCoreUploadTraitTest.php, tests/Smartling/ContentTypes/ExternalContentManagerTest.php, tests/Smartling/ContentTypes/ExternalContentYoastTest.php, tests/Smartling/Helpers/FieldsFilterHelperTest.php, tests/Smartling/Helpers/GutenbergBlockHelperTest.php, tests/Smartling/Helpers/ShortcodeHelperTest.php
refactoring to get rid of setting field filter parameters to DI
=> refactor (WP-875)

inc/Smartling/DbAl/MultilingualPress3Connector.php
Inpsyde state that this should not need any changes, adding debug for now
=> add debug (WP-876)

composer.json, inc/Smartling/Jobs/LastModifiedCheckJob.php, inc/Smartling/Services/ContentRelationsDiscoveryService.php, readme.txt, smartling-connector.php
No actual issues other than content not authorised for translation. Also removes a log error, that doesn't affect plugin functionality
=> fix auto-autorize and check status crons (WP-891)

composer.json, inc/Smartling/Bootstrap.php, inc/Smartling/Jobs/DownloadTranslationJob.php, inc/Smartling/Jobs/JobAbstract.php, inc/Smartling/Jobs/JobInterface.php, inc/Smartling/Jobs/LastModifiedCheckJob.php, inc/Smartling/Jobs/SubmissionCollectorJob.php, inc/Smartling/Jobs/UploadJob.php, readme.txt, smartling-connector.php, tests/Jobs/LastModifiedCheckJobTest.php
visibility PR, only logging changed
=> add debug (WP-910)

composer.json, inc/Smartling/Bootstrap.php, inc/Smartling/ContentTypes/Elementor/Elements/UcAddonLogoMarquee.php, inc/Smartling/ContentTypes/ExternalContentElementor.php, inc/Smartling/Jobs/DownloadTranslationJob.php, inc/Smartling/Jobs/JobAbstract.php, inc/Smartling/Jobs/LastModifiedCheckJob.php, inc/Smartling/Jobs/SubmissionCollectorJob.php, inc/Smartling/Jobs/UploadJob.php, inc/Smartling/Queue/Queue.php, inc/Smartling/Services/GlobalSettingsManager.php, inc/Smartling/Settings/SettingsManager.php, inc/Smartling/WP/Controller/ConfigurationProfilesController.php, inc/Smartling/WP/Table/QueueManagerTableWidget.php, inc/Smartling/WP/View/ConfigurationProfiles.php, inc/config/cron.yml, inc/config/services.yml, js/configuration-profile-form.js, js/smartling-connector-gutenberg-lock-attributes.js, readme.txt, smartling-connector.php, tests/Jobs/LastModifiedCheckJobTest.php, tests/Smartling/ContentTypes/ExternalContentElementorTest.php, tests/Smartling/ContentTypes/wp-944.json, tests/Smartling/WP/Controller/ConfigurationProfilesControllerTest.php
Check if lock present on page load, display relevant message if it is
=> add setting to control cron lock ttl, improve queues UI (WP-942)

composer.json, inc/Smartling/Extensions/Acf/AcfDynamicSupport.php, inc/Smartling/Helpers/DetectChangesHelper.php, inc/Smartling/Helpers/WordpressFunctionProxyHelper.php, inc/Smartling/WP/Controller/PostBasedWidgetControllerStd.php, inc/config/services.yml, readme.txt, smartling-connector.php, tests/DetectChangesTest.php, tests/Smartling/Extensions/Acf/AcfDynamicSupportTest.php, tests/Smartling/Extensions/Acf/AcfTypeDetectorTest.php, tests/Smartling/Helpers/DetectChangesHelperTest.php, tests/Smartling/Helpers/GutenbergBlockHelperTest.php
No stable version change because this needs some additional work on the UI to release.
For now I'll manually insert the submissions required for this to work.
=> add ACF field group synchronization (WP-943)

inc/Smartling/Extensions/Acf/AcfDynamicSupport.php, inc/Smartling/Services/BlogRemovalHandler.php, inc/Smartling/Settings/ConfigurationProfileEntity.php, inc/Smartling/Settings/SettingsManager.php, inc/Smartling/WP/Controller/ConfigurationProfileFormController.php, inc/Smartling/WP/Table/BulkSubmitTableWidget.php, inc/Smartling/WP/View/ConfigurationProfileForm.php, plugin-examples/mlp3-migrate.php, tests/IntegrationTests/SmartlingUnitTestCaseAbstract.php, tests/Services/BlogRemovalHandlerTest.php, tests/Smartling/WP/Table/BulkSubmitTableWidgetTest.php
visibility PR, from https://github.com/Smartling/wordpress-localization-plugin/pull/572#discussion_r2239674411
=> rename ConfigurationProfileEntity methods

composer.json, inc/Smartling/WP/Controller/ConfigurationProfilesController.php, inc/Smartling/WP/Table/QueueManagerTableWidget.php, inc/config/services.yml, readme.txt, smartling-connector.php, tests/Smartling/WP/Controller/ConfigurationProfilesControllerTest.php
=> Fix fatal (WP-958)
